version: '3.8'
services:
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    ports:
      - "8082:8082"
      - "5055:5055"
    volumes:
      - traccar-logs:/opt/traccar/logs
      - traccar-conf:/opt/traccar/conf
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: traccar-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: umasenhastrongaqui
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar
      MYSQL_PASSWORD: senhadobanco
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  traccar-logs:
  traccar-conf:
  mysql-data:
